### ISSUE TITLE
Reader SCARD_SHARE_DIRECT connection error

### ISSUE THREAD

**Issue by Klemen1337** [santigimeno/node-pcsclite#49] opened 2015-12-03 09:06 UTC
Hi,
I am trying to connect to the reader with direct mode to write on LCD. It works on Linux, but not on Windows. Are the drivers different?

```
var LCD_CONTRAST = new Buffer([0xFF, 0x00, 0x6C, 0x00, 0x00]);

clearScreen: function (reader) {
    reader.connect({ share_mode: reader_object.SCARD_SHARE_DIRECT }, function (err, protocol) {
        reader.transmit(LCD_CLEAR, 40, reader.SCARD_PROTOCOL_RAW, function (err, data) {
            if (err) {
                console.log('error clearing screen:', err);
            }
        });
    });
}
```

I get [Error: SCardConnect error: Smart card was removed <0x8010069>] while trying to connect.

Cheers,
K

**Comment by santigimeno** [comment] 2015-12-03 09:19
@Klemen1337 I really don't know. What reader are you using? Does it have proprietary drivers? Do they distribute sample code to write on the LCD?

**Comment by Klemen1337** [comment] 2015-12-03 09:26
I am using ACR1222L reader with drivers from the official page. I can pickup state changes like the example code, but cant transmit direct commands. The same code works on Linux, but not Windows.

**Comment by LudovicRousseau** [comment] 2015-12-03 09:28
The Windows CCID driver is far from perfect. The GNU/Linux one is much better :-)

Try again with a card inserted in the reader.

**Comment by Klemen1337** [comment] 2015-12-03 09:32
@LudovicRousseau yea I figured that out :stuck_out_tongue_winking_eye: It works if state is SCARD_STATE_PRESENT, but It is not how I want it to work.

**Comment by LudovicRousseau** [comment] 2015-12-03 10:50
@Klemen1337 maybe ACS has a better driver.

**Comment by Klemen1337** [comment] 2015-12-03 13:51
@LudovicRousseau ACS drivers are the one I used...

**Comment by santigimeno** [comment] 2015-12-03 15:03
@Klemen1337 aren't there code samples for the functionality you're testing in their drivers / documentation? If there are and they work maybe we can *migrate* it to use node-pcsclite.

**Comment by LudovicRousseau** [comment] 2015-12-03 15:08
I do not use Windows so I am not sure of what I write.
I would not be surprised if you can't connect to a reader with no card inserted, even with SCARD_SHARE_DIRECT. Your bug would then be a limitation PC/SC on Windows and not a bug in node-pcsclite.

**Comment by santigimeno** [comment] 2016-02-23 14:24
I'm closing this. @Klemen1337 please reopen the issue if you think there's something actionable. Thanks

**Closed by santigimeno** 2016-02-23 14:24 UTC
